name: NekolPunishments
version: 1.4
main: dev.hypinohaizin.NekolPunishments
author: Hypinohaizin
description: Ban,Kick,UnBan
commands:
  kick:
    description: Kick a player
  tempban:
    description: Temporarily ban a player
  ban:
    description: Permanently ban a player
  unban:
    description: Unban a player